server:
  port: 9080
  servlet:
    session:
      cookie:
        secure: true
      timeout: 60
  tomcat:
    uri-encoding: UTF-8
    max-threads: 500
    accept-count: 1000
  connection-timeout: 20000

spring:
  application:
    name: spring-boot-seed

  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true

  datasource:
    druid:
      initial-size: 1
      max-active: 20
      min-idle: 1
      max-wait: 6000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      use-global-data-source-stat: true
      filters: stat,wall
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: druid
        login-password: druid
      main:
        url: jdbc:mysql://localhost:3306/springmvc
        username: root
        password: root

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    show-sql: true

  cache:
    type: redis

  redis:
    host: localhost
    port: 6379
    password:
    timeout: 10s

  jackson:
    default-property-inclusion: non_null
    time-zone: GMT+8

  task:
    execution:
      pool:
        core-size: 9
        max-size: 18
        queue-capacity: 1000
        keep-alive: 60s

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

management:
  endpoints:
    web:
      exposure:
        include: prometheus

  metrics:
    tags:
      application: ${spring.application.name}

jwt:
  subject: admin
  key: whosyourdaddy